/*
Copyright 2023 The IOMesh Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	sfsv1 "github.com/iomesh/sfs-sdk-go/pkg/apis/arcfra.com/sfs/v1"
	versioned "github.com/iomesh/sfs-sdk-go/pkg/client/arcfra.com/clientset/versioned"
	internalinterfaces "github.com/iomesh/sfs-sdk-go/pkg/client/arcfra.com/informers/externalversions/internalinterfaces"
	v1 "github.com/iomesh/sfs-sdk-go/pkg/client/arcfra.com/listers/sfs/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CloudProviderInformer provides access to a shared informer and lister for
// CloudProviders.
type CloudProviderInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.CloudProviderLister
}

type cloudProviderInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCloudProviderInformer constructs a new informer for CloudProvider type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCloudProviderInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCloudProviderInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCloudProviderInformer constructs a new informer for CloudProvider type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCloudProviderInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SfsV1().CloudProviders(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SfsV1().CloudProviders(namespace).Watch(context.TODO(), options)
			},
		},
		&sfsv1.CloudProvider{},
		resyncPeriod,
		indexers,
	)
}

func (f *cloudProviderInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCloudProviderInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *cloudProviderInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&sfsv1.CloudProvider{}, f.defaultInformer)
}

func (f *cloudProviderInformer) Lister() v1.CloudProviderLister {
	return v1.NewCloudProviderLister(f.Informer().GetIndexer())
}
