/*
Copyright 2023 The IOMesh Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/iomesh/sfs-sdk-go/pkg/apis/iomesh.io/sfs/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNodeHealths implements NodeHealthInterface
type FakeNodeHealths struct {
	Fake *FakeSfsV1
	ns   string
}

var nodehealthsResource = v1.SchemeGroupVersion.WithResource("nodehealths")

var nodehealthsKind = v1.SchemeGroupVersion.WithKind("NodeHealth")

// Get takes name of the nodeHealth, and returns the corresponding nodeHealth object, and an error if there is any.
func (c *FakeNodeHealths) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.NodeHealth, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(nodehealthsResource, c.ns, name), &v1.NodeHealth{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.NodeHealth), err
}

// List takes label and field selectors, and returns the list of NodeHealths that match those selectors.
func (c *FakeNodeHealths) List(ctx context.Context, opts metav1.ListOptions) (result *v1.NodeHealthList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(nodehealthsResource, nodehealthsKind, c.ns, opts), &v1.NodeHealthList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.NodeHealthList{ListMeta: obj.(*v1.NodeHealthList).ListMeta}
	for _, item := range obj.(*v1.NodeHealthList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nodeHealths.
func (c *FakeNodeHealths) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(nodehealthsResource, c.ns, opts))

}

// Create takes the representation of a nodeHealth and creates it.  Returns the server's representation of the nodeHealth, and an error, if there is any.
func (c *FakeNodeHealths) Create(ctx context.Context, nodeHealth *v1.NodeHealth, opts metav1.CreateOptions) (result *v1.NodeHealth, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(nodehealthsResource, c.ns, nodeHealth), &v1.NodeHealth{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.NodeHealth), err
}

// Update takes the representation of a nodeHealth and updates it. Returns the server's representation of the nodeHealth, and an error, if there is any.
func (c *FakeNodeHealths) Update(ctx context.Context, nodeHealth *v1.NodeHealth, opts metav1.UpdateOptions) (result *v1.NodeHealth, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(nodehealthsResource, c.ns, nodeHealth), &v1.NodeHealth{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.NodeHealth), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNodeHealths) UpdateStatus(ctx context.Context, nodeHealth *v1.NodeHealth, opts metav1.UpdateOptions) (*v1.NodeHealth, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(nodehealthsResource, "status", c.ns, nodeHealth), &v1.NodeHealth{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.NodeHealth), err
}

// Delete takes name of the nodeHealth and deletes it. Returns an error if one occurs.
func (c *FakeNodeHealths) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(nodehealthsResource, c.ns, name, opts), &v1.NodeHealth{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNodeHealths) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(nodehealthsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.NodeHealthList{})
	return err
}

// Patch applies the patch and returns the patched nodeHealth.
func (c *FakeNodeHealths) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.NodeHealth, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nodehealthsResource, c.ns, name, pt, data, subresources...), &v1.NodeHealth{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.NodeHealth), err
}
