/*
Copyright 2023 The IOMesh Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/iomesh/sfs-sdk-go/pkg/apis/iomesh.io/sfs/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeShards implements ShardInterface
type FakeShards struct {
	Fake *FakeSfsV1
	ns   string
}

var shardsResource = v1.SchemeGroupVersion.WithResource("shards")

var shardsKind = v1.SchemeGroupVersion.WithKind("Shard")

// Get takes name of the shard, and returns the corresponding shard object, and an error if there is any.
func (c *FakeShards) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Shard, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(shardsResource, c.ns, name), &v1.Shard{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Shard), err
}

// List takes label and field selectors, and returns the list of Shards that match those selectors.
func (c *FakeShards) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ShardList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(shardsResource, shardsKind, c.ns, opts), &v1.ShardList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.ShardList{ListMeta: obj.(*v1.ShardList).ListMeta}
	for _, item := range obj.(*v1.ShardList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested shards.
func (c *FakeShards) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(shardsResource, c.ns, opts))

}

// Create takes the representation of a shard and creates it.  Returns the server's representation of the shard, and an error, if there is any.
func (c *FakeShards) Create(ctx context.Context, shard *v1.Shard, opts metav1.CreateOptions) (result *v1.Shard, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(shardsResource, c.ns, shard), &v1.Shard{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Shard), err
}

// Update takes the representation of a shard and updates it. Returns the server's representation of the shard, and an error, if there is any.
func (c *FakeShards) Update(ctx context.Context, shard *v1.Shard, opts metav1.UpdateOptions) (result *v1.Shard, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(shardsResource, c.ns, shard), &v1.Shard{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Shard), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeShards) UpdateStatus(ctx context.Context, shard *v1.Shard, opts metav1.UpdateOptions) (*v1.Shard, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(shardsResource, "status", c.ns, shard), &v1.Shard{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Shard), err
}

// Delete takes name of the shard and deletes it. Returns an error if one occurs.
func (c *FakeShards) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(shardsResource, c.ns, name, opts), &v1.Shard{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeShards) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(shardsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.ShardList{})
	return err
}

// Patch applies the patch and returns the patched shard.
func (c *FakeShards) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Shard, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(shardsResource, c.ns, name, pt, data, subresources...), &v1.Shard{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Shard), err
}
