/*
Copyright 2023 The IOMesh Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// CloudProviderListerExpansion allows custom methods to be added to
// CloudProviderLister.
type CloudProviderListerExpansion interface{}

// CloudProviderNamespaceListerExpansion allows custom methods to be added to
// CloudProviderNamespaceLister.
type CloudProviderNamespaceListerExpansion interface{}

// ClusterListerExpansion allows custom methods to be added to
// ClusterLister.
type ClusterListerExpansion interface{}

// ClusterNamespaceListerExpansion allows custom methods to be added to
// ClusterNamespaceLister.
type ClusterNamespaceListerExpansion interface{}

// MetricListerExpansion allows custom methods to be added to
// MetricLister.
type MetricListerExpansion interface{}

// MetricNamespaceListerExpansion allows custom methods to be added to
// MetricNamespaceLister.
type MetricNamespaceListerExpansion interface{}

// NamespaceListerExpansion allows custom methods to be added to
// NamespaceLister.
type NamespaceListerExpansion interface{}

// NamespaceNamespaceListerExpansion allows custom methods to be added to
// NamespaceNamespaceLister.
type NamespaceNamespaceListerExpansion interface{}

// NodeListerExpansion allows custom methods to be added to
// NodeLister.
type NodeListerExpansion interface{}

// NodeNamespaceListerExpansion allows custom methods to be added to
// NodeNamespaceLister.
type NodeNamespaceListerExpansion interface{}

// NodeHealthListerExpansion allows custom methods to be added to
// NodeHealthLister.
type NodeHealthListerExpansion interface{}

// NodeHealthNamespaceListerExpansion allows custom methods to be added to
// NodeHealthNamespaceLister.
type NodeHealthNamespaceListerExpansion interface{}

// RecoveryDatabaseListerExpansion allows custom methods to be added to
// RecoveryDatabaseLister.
type RecoveryDatabaseListerExpansion interface{}

// RecoveryDatabaseNamespaceListerExpansion allows custom methods to be added to
// RecoveryDatabaseNamespaceLister.
type RecoveryDatabaseNamespaceListerExpansion interface{}

// SessionListerExpansion allows custom methods to be added to
// SessionLister.
type SessionListerExpansion interface{}

// SessionNamespaceListerExpansion allows custom methods to be added to
// SessionNamespaceLister.
type SessionNamespaceListerExpansion interface{}

// ShardListerExpansion allows custom methods to be added to
// ShardLister.
type ShardListerExpansion interface{}

// ShardNamespaceListerExpansion allows custom methods to be added to
// ShardNamespaceLister.
type ShardNamespaceListerExpansion interface{}

// VipListerExpansion allows custom methods to be added to
// VipLister.
type VipListerExpansion interface{}

// VipNamespaceListerExpansion allows custom methods to be added to
// VipNamespaceLister.
type VipNamespaceListerExpansion interface{}

// VolumeListerExpansion allows custom methods to be added to
// VolumeLister.
type VolumeListerExpansion interface{}

// VolumeNamespaceListerExpansion allows custom methods to be added to
// VolumeNamespaceLister.
type VolumeNamespaceListerExpansion interface{}
