/*
Copyright 2023 The IOMesh Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	sfsv1 "github.com/iomesh/sfs-sdk-go/pkg/apis/iomesh.io/sfs/v1"
	versioned "github.com/iomesh/sfs-sdk-go/pkg/client/iomesh.io/clientset/versioned"
	internalinterfaces "github.com/iomesh/sfs-sdk-go/pkg/client/iomesh.io/informers/externalversions/internalinterfaces"
	v1 "github.com/iomesh/sfs-sdk-go/pkg/client/iomesh.io/listers/sfs/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ManagementVipInformer provides access to a shared informer and lister for
// ManagementVips.
type ManagementVipInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ManagementVipLister
}

type managementVipInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewManagementVipInformer constructs a new informer for ManagementVip type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewManagementVipInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredManagementVipInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredManagementVipInformer constructs a new informer for ManagementVip type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredManagementVipInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SfsV1().ManagementVips(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SfsV1().ManagementVips(namespace).Watch(context.TODO(), options)
			},
		},
		&sfsv1.ManagementVip{},
		resyncPeriod,
		indexers,
	)
}

func (f *managementVipInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredManagementVipInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *managementVipInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&sfsv1.ManagementVip{}, f.defaultInformer)
}

func (f *managementVipInformer) Lister() v1.ManagementVipLister {
	return v1.NewManagementVipLister(f.Informer().GetIndexer())
}
