/*
Copyright 2023 The IOMesh Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/iomesh/sfs-sdk-go/pkg/apis/sfs.iomesh.io/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCloudProviders implements CloudProviderInterface
type FakeCloudProviders struct {
	Fake *FakeSfsV1
	ns   string
}

var cloudprovidersResource = v1.SchemeGroupVersion.WithResource("cloudproviders")

var cloudprovidersKind = v1.SchemeGroupVersion.WithKind("CloudProvider")

// Get takes name of the cloudProvider, and returns the corresponding cloudProvider object, and an error if there is any.
func (c *FakeCloudProviders) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.CloudProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(cloudprovidersResource, c.ns, name), &v1.CloudProvider{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.CloudProvider), err
}

// List takes label and field selectors, and returns the list of CloudProviders that match those selectors.
func (c *FakeCloudProviders) List(ctx context.Context, opts metav1.ListOptions) (result *v1.CloudProviderList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(cloudprovidersResource, cloudprovidersKind, c.ns, opts), &v1.CloudProviderList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.CloudProviderList{ListMeta: obj.(*v1.CloudProviderList).ListMeta}
	for _, item := range obj.(*v1.CloudProviderList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cloudProviders.
func (c *FakeCloudProviders) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(cloudprovidersResource, c.ns, opts))

}

// Create takes the representation of a cloudProvider and creates it.  Returns the server's representation of the cloudProvider, and an error, if there is any.
func (c *FakeCloudProviders) Create(ctx context.Context, cloudProvider *v1.CloudProvider, opts metav1.CreateOptions) (result *v1.CloudProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(cloudprovidersResource, c.ns, cloudProvider), &v1.CloudProvider{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.CloudProvider), err
}

// Update takes the representation of a cloudProvider and updates it. Returns the server's representation of the cloudProvider, and an error, if there is any.
func (c *FakeCloudProviders) Update(ctx context.Context, cloudProvider *v1.CloudProvider, opts metav1.UpdateOptions) (result *v1.CloudProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(cloudprovidersResource, c.ns, cloudProvider), &v1.CloudProvider{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.CloudProvider), err
}

// Delete takes name of the cloudProvider and deletes it. Returns an error if one occurs.
func (c *FakeCloudProviders) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(cloudprovidersResource, c.ns, name, opts), &v1.CloudProvider{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCloudProviders) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(cloudprovidersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.CloudProviderList{})
	return err
}

// Patch applies the patch and returns the patched cloudProvider.
func (c *FakeCloudProviders) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.CloudProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(cloudprovidersResource, c.ns, name, pt, data, subresources...), &v1.CloudProvider{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.CloudProvider), err
}
