/*
Copyright 2023 The IOMesh Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/iomesh/sfs-sdk-go/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// CloudProviders returns a CloudProviderInformer.
	CloudProviders() CloudProviderInformer
	// Clusters returns a ClusterInformer.
	Clusters() ClusterInformer
	// Licenses returns a LicenseInformer.
	Licenses() LicenseInformer
	// Metrics returns a MetricInformer.
	Metrics() MetricInformer
	// Namespaces returns a NamespaceInformer.
	Namespaces() NamespaceInformer
	// Nodes returns a NodeInformer.
	Nodes() NodeInformer
	// NodeHealths returns a NodeHealthInformer.
	NodeHealths() NodeHealthInformer
	// RecoveryDatabases returns a RecoveryDatabaseInformer.
	RecoveryDatabases() RecoveryDatabaseInformer
	// Routes returns a RouteInformer.
	Routes() RouteInformer
	// Sessions returns a SessionInformer.
	Sessions() SessionInformer
	// Shards returns a ShardInformer.
	Shards() ShardInformer
	// Vips returns a VipInformer.
	Vips() VipInformer
	// Volumes returns a VolumeInformer.
	Volumes() VolumeInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// CloudProviders returns a CloudProviderInformer.
func (v *version) CloudProviders() CloudProviderInformer {
	return &cloudProviderInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Clusters returns a ClusterInformer.
func (v *version) Clusters() ClusterInformer {
	return &clusterInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Licenses returns a LicenseInformer.
func (v *version) Licenses() LicenseInformer {
	return &licenseInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Metrics returns a MetricInformer.
func (v *version) Metrics() MetricInformer {
	return &metricInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Namespaces returns a NamespaceInformer.
func (v *version) Namespaces() NamespaceInformer {
	return &namespaceInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Nodes returns a NodeInformer.
func (v *version) Nodes() NodeInformer {
	return &nodeInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// NodeHealths returns a NodeHealthInformer.
func (v *version) NodeHealths() NodeHealthInformer {
	return &nodeHealthInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// RecoveryDatabases returns a RecoveryDatabaseInformer.
func (v *version) RecoveryDatabases() RecoveryDatabaseInformer {
	return &recoveryDatabaseInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Routes returns a RouteInformer.
func (v *version) Routes() RouteInformer {
	return &routeInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Sessions returns a SessionInformer.
func (v *version) Sessions() SessionInformer {
	return &sessionInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Shards returns a ShardInformer.
func (v *version) Shards() ShardInformer {
	return &shardInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Vips returns a VipInformer.
func (v *version) Vips() VipInformer {
	return &vipInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Volumes returns a VolumeInformer.
func (v *version) Volumes() VolumeInformer {
	return &volumeInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
